### ISSUE TITLE
Correct typo in method name 'sirenLinkDisocoverer()' in class 'SirenMediaTypeConfiguration'

### ISSUE THREAD

**Issue by toedter** [ingogriebsch/spring-hateoas-siren#247]
In class SirenMediaTypeConfiguration, line 109:

```
LinkDiscoverer sirenLinkDisocoverer() {
                           ^
```
should be renamed to:

`LinkDiscoverer sirenLinkDiscoverer() {`

**Comment by ingogriebsch** [comment]
Thanks for the hint, @toedter ! :)

**Comment by toedter** [comment]
Funny thing, I started to implement a JsonApiLInkDiscoverer and was interested in your implementation. And so I stumbled about it :)

**Comment by ingogriebsch** [comment]
Done!
