### ISSUE TITLE
Publishing to Maven Central

### ISSUE THREAD

**Issue by hollesse** [ingogriebsch/spring-hateoas-siren#32]
Is it possible that you could publish your project to Maven Central?

**Comment by ingogriebsch** [comment]
Hi @hollesse yeah, that's the plan. I'm just updating the documentation. Releasing a first version of the library will be the next step. :)

**Comment by hollesse** [comment]
Hi @ingogriebsch that would be great! We have to consume a siren API and your work looks really great! Looking forward to find your library in maven central soon

**Comment by ingogriebsch** [comment]
Hey @hollesse You will now find the current SNAPSHOT version on Sonatypes Snapshots Repository.
Please check the README for further details. A link to the updated documentation is also available there.

**Comment by ingogriebsch** [comment]
Hey @hollesse You will now find the first Milestone version on Maven Central.
Please check the README for further details. A link to the updated documentation is also available there.

**Comment by hollesse** [comment]
Hey thank you very much. For out system we just implemented a client which could consume the external siren API we need. But if we have to use another siren API in the future we will come back and have a look! Thank you for your work! I think it is a great project :)
