### ISSUE TITLE
Clarify how to provide an AffordanceModelFactory

### ISSUE THREAD

**Issue by ingogriebsch** [ingogriebsch/spring-hateoas-siren#52]
@gregturn I would like to understand how a custom mediatype should provide an `AffordanceModelFactory` implementation? I'm currently using a `spring.factories` file and declare a `org.springframework.hateoas.mediatype.AffordanceModelFactory` entry referencing the Siren related factory class.

https://github.com/ingogriebsch/spring-hateoas-siren/blob/99dd0f6dcfe29657f54a643c80eacbe018ecccd8/src/main/resources/META-INF/spring.factories#L1

It works but is it also the way to go?

**Comment by gregturn** [comment]
That's the way!

(You can simply drop the `MediaTypeConfigurationProvider` part of your `spring.factories`.)

**Comment by ingogriebsch** [comment]
Thanks! :)

**Comment by ingogriebsch** [comment]
Done!
